name: Close Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Delete
      run: git push origin --delete ${{github.event.pull_request.head.ref}}
